// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_profile.proto

package user_profile

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreatePasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordRequest) Reset()         { *m = CreatePasswordRequest{} }
func (m *CreatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordRequest) ProtoMessage()    {}
func (*CreatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49b5b3a45c8a339, []int{0}
}

func (m *CreatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordRequest.Unmarshal(m, b)
}
func (m *CreatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordRequest.Marshal(b, m, deterministic)
}
func (m *CreatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordRequest.Merge(m, src)
}
func (m *CreatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordRequest.Size(m)
}
func (m *CreatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordRequest proto.InternalMessageInfo

func (m *CreatePasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreatePasswordResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordResponse) Reset()         { *m = CreatePasswordResponse{} }
func (m *CreatePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordResponse) ProtoMessage()    {}
func (*CreatePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49b5b3a45c8a339, []int{1}
}

func (m *CreatePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordResponse.Unmarshal(m, b)
}
func (m *CreatePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordResponse.Marshal(b, m, deterministic)
}
func (m *CreatePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordResponse.Merge(m, src)
}
func (m *CreatePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordResponse.Size(m)
}
func (m *CreatePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordResponse proto.InternalMessageInfo

func (m *CreatePasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*CreatePasswordRequest)(nil), "user_profile.CreatePasswordRequest")
	proto.RegisterType((*CreatePasswordResponse)(nil), "user_profile.CreatePasswordResponse")
}

func init() { proto.RegisterFile("user_profile.proto", fileDescriptor_b49b5b3a45c8a339) }

var fileDescriptor_b49b5b3a45c8a339 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2d, 0x4e, 0x2d,
	0x8a, 0x2f, 0x28, 0xca, 0x4f, 0xcb, 0xcc, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x41, 0x16, 0x93, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f,
	0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xa8, 0x55, 0xf2, 0xe4, 0x12,
	0x75, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x48, 0x2c, 0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0x09, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0x4d, 0xcd, 0x4d, 0xcc, 0xcc, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0xa4, 0xb8, 0x38, 0x0a, 0xa0, 0x0a, 0x25, 0x98,
	0xc0, 0x12, 0x70, 0xbe, 0x92, 0x11, 0x97, 0x18, 0xba, 0x51, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9,
	0x42, 0x12, 0x5c, 0xec, 0xc5, 0xa5, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5, 0x60, 0xd3, 0x38, 0x82, 0x60,
	0x5c, 0xa3, 0x4e, 0x46, 0x2e, 0xbe, 0xd0, 0xe2, 0xd4, 0xa2, 0x00, 0x88, 0x63, 0x1d, 0x03, 0x3c,
	0x85, 0xca, 0xb9, 0xf8, 0x50, 0x8d, 0x11, 0x52, 0xd6, 0x43, 0xf1, 0x24, 0x56, 0xf7, 0x4a, 0xa9,
	0xe0, 0x57, 0x04, 0x71, 0x89, 0x92, 0x54, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0x44, 0x94, 0xf8, 0xf5,
	0x93, 0xc1, 0x0a, 0x60, 0x8e, 0xb7, 0x62, 0xd4, 0x4a, 0x62, 0x03, 0x87, 0x88, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xe4, 0x94, 0x01, 0x2e, 0x53, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserProfileAPIClient is the client API for UserProfileAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserProfileAPIClient interface {
	CreatePassword(ctx context.Context, in *CreatePasswordRequest, opts ...grpc.CallOption) (*CreatePasswordResponse, error)
}

type userProfileAPIClient struct {
	cc *grpc.ClientConn
}

func NewUserProfileAPIClient(cc *grpc.ClientConn) UserProfileAPIClient {
	return &userProfileAPIClient{cc}
}

func (c *userProfileAPIClient) CreatePassword(ctx context.Context, in *CreatePasswordRequest, opts ...grpc.CallOption) (*CreatePasswordResponse, error) {
	out := new(CreatePasswordResponse)
	err := c.cc.Invoke(ctx, "/user_profile.UserProfileAPI/CreatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProfileAPIServer is the server API for UserProfileAPI service.
type UserProfileAPIServer interface {
	CreatePassword(context.Context, *CreatePasswordRequest) (*CreatePasswordResponse, error)
}

func RegisterUserProfileAPIServer(s *grpc.Server, srv UserProfileAPIServer) {
	s.RegisterService(&_UserProfileAPI_serviceDesc, srv)
}

func _UserProfileAPI_CreatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileAPIServer).CreatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_profile.UserProfileAPI/CreatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileAPIServer).CreatePassword(ctx, req.(*CreatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserProfileAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_profile.UserProfileAPI",
	HandlerType: (*UserProfileAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePassword",
			Handler:    _UserProfileAPI_CreatePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_profile.proto",
}
