// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/user_profile.proto

package user_profile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreatePasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordRequest) Reset()         { *m = CreatePasswordRequest{} }
func (m *CreatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordRequest) ProtoMessage()    {}
func (*CreatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef67784dca69381c, []int{0}
}

func (m *CreatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordRequest.Unmarshal(m, b)
}
func (m *CreatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordRequest.Marshal(b, m, deterministic)
}
func (m *CreatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordRequest.Merge(m, src)
}
func (m *CreatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordRequest.Size(m)
}
func (m *CreatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordRequest proto.InternalMessageInfo

func (m *CreatePasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreatePasswordResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePasswordResponse) Reset()         { *m = CreatePasswordResponse{} }
func (m *CreatePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePasswordResponse) ProtoMessage()    {}
func (*CreatePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef67784dca69381c, []int{1}
}

func (m *CreatePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePasswordResponse.Unmarshal(m, b)
}
func (m *CreatePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePasswordResponse.Marshal(b, m, deterministic)
}
func (m *CreatePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePasswordResponse.Merge(m, src)
}
func (m *CreatePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePasswordResponse.Size(m)
}
func (m *CreatePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePasswordResponse proto.InternalMessageInfo

func (m *CreatePasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UserProfileRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfileRequest) Reset()         { *m = UserProfileRequest{} }
func (m *UserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UserProfileRequest) ProtoMessage()    {}
func (*UserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef67784dca69381c, []int{2}
}

func (m *UserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileRequest.Unmarshal(m, b)
}
func (m *UserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileRequest.Marshal(b, m, deterministic)
}
func (m *UserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileRequest.Merge(m, src)
}
func (m *UserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UserProfileRequest.Size(m)
}
func (m *UserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileRequest proto.InternalMessageInfo

func (m *UserProfileRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserProfileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfileResponse) Reset()         { *m = UserProfileResponse{} }
func (m *UserProfileResponse) String() string { return proto.CompactTextString(m) }
func (*UserProfileResponse) ProtoMessage()    {}
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef67784dca69381c, []int{3}
}

func (m *UserProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileResponse.Unmarshal(m, b)
}
func (m *UserProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileResponse.Marshal(b, m, deterministic)
}
func (m *UserProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileResponse.Merge(m, src)
}
func (m *UserProfileResponse) XXX_Size() int {
	return xxx_messageInfo_UserProfileResponse.Size(m)
}
func (m *UserProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileResponse proto.InternalMessageInfo

func (m *UserProfileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserProfileResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfileResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserProfileResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserProfileResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type UserProfileResponse_SecretCode struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sent                 bool     `protobuf:"varint,2,opt,name=sent,proto3" json:"sent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfileResponse_SecretCode) Reset()         { *m = UserProfileResponse_SecretCode{} }
func (m *UserProfileResponse_SecretCode) String() string { return proto.CompactTextString(m) }
func (*UserProfileResponse_SecretCode) ProtoMessage()    {}
func (*UserProfileResponse_SecretCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef67784dca69381c, []int{3, 0}
}

func (m *UserProfileResponse_SecretCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileResponse_SecretCode.Unmarshal(m, b)
}
func (m *UserProfileResponse_SecretCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileResponse_SecretCode.Marshal(b, m, deterministic)
}
func (m *UserProfileResponse_SecretCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileResponse_SecretCode.Merge(m, src)
}
func (m *UserProfileResponse_SecretCode) XXX_Size() int {
	return xxx_messageInfo_UserProfileResponse_SecretCode.Size(m)
}
func (m *UserProfileResponse_SecretCode) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileResponse_SecretCode.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileResponse_SecretCode proto.InternalMessageInfo

func (m *UserProfileResponse_SecretCode) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *UserProfileResponse_SecretCode) GetSent() bool {
	if m != nil {
		return m.Sent
	}
	return false
}

type UserProfileResponse_Projects struct {
	ProjectIds           []string `protobuf:"bytes,1,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfileResponse_Projects) Reset()         { *m = UserProfileResponse_Projects{} }
func (m *UserProfileResponse_Projects) String() string { return proto.CompactTextString(m) }
func (*UserProfileResponse_Projects) ProtoMessage()    {}
func (*UserProfileResponse_Projects) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef67784dca69381c, []int{3, 1}
}

func (m *UserProfileResponse_Projects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileResponse_Projects.Unmarshal(m, b)
}
func (m *UserProfileResponse_Projects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileResponse_Projects.Marshal(b, m, deterministic)
}
func (m *UserProfileResponse_Projects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileResponse_Projects.Merge(m, src)
}
func (m *UserProfileResponse_Projects) XXX_Size() int {
	return xxx_messageInfo_UserProfileResponse_Projects.Size(m)
}
func (m *UserProfileResponse_Projects) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileResponse_Projects.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileResponse_Projects proto.InternalMessageInfo

func (m *UserProfileResponse_Projects) GetProjectIds() []string {
	if m != nil {
		return m.ProjectIds
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatePasswordRequest)(nil), "user_profile.CreatePasswordRequest")
	proto.RegisterType((*CreatePasswordResponse)(nil), "user_profile.CreatePasswordResponse")
	proto.RegisterType((*UserProfileRequest)(nil), "user_profile.UserProfileRequest")
	proto.RegisterType((*UserProfileResponse)(nil), "user_profile.UserProfileResponse")
	proto.RegisterType((*UserProfileResponse_SecretCode)(nil), "user_profile.UserProfileResponse.SecretCode")
	proto.RegisterType((*UserProfileResponse_Projects)(nil), "user_profile.UserProfileResponse.Projects")
}

func init() { proto.RegisterFile("protos/user_profile.proto", fileDescriptor_ef67784dca69381c) }

var fileDescriptor_ef67784dca69381c = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0x96, 0x0d, 0xb4, 0x66, 0x40, 0x54, 0xdd, 0xd2, 0xd6, 0xb5, 0x90, 0x4a, 0xdd, 0x1e, 0x10,
	0x95, 0xb0, 0x44, 0xa5, 0x1e, 0xb8, 0x55, 0x9c, 0xb8, 0x54, 0x96, 0xab, 0x9e, 0xd1, 0xc6, 0x1e,
	0x90, 0x13, 0xe3, 0x75, 0x76, 0xd6, 0xe1, 0x1a, 0xe5, 0x15, 0xf2, 0x68, 0x79, 0x85, 0x3c, 0x43,
	0xce, 0x11, 0x6b, 0x3b, 0xe0, 0xfc, 0x90, 0xdb, 0x7e, 0x33, 0xdf, 0x7e, 0x33, 0xf3, 0xcd, 0xc0,
	0x97, 0x4c, 0x0a, 0x25, 0xc8, 0xcb, 0x09, 0xe5, 0x32, 0x93, 0x62, 0x15, 0x27, 0x38, 0xd1, 0x31,
	0xd6, 0x3d, 0x8c, 0x39, 0x83, 0xb5, 0x10, 0xeb, 0x04, 0x3d, 0x9e, 0xc5, 0x1e, 0x4f, 0x53, 0xa1,
	0xb8, 0x8a, 0x45, 0x4a, 0x05, 0xd7, 0x5d, 0xc0, 0xc7, 0xb9, 0x44, 0xae, 0xd0, 0xe7, 0x44, 0x5b,
	0x21, 0xa3, 0x00, 0xcf, 0x73, 0x24, 0xc5, 0xfa, 0xd0, 0xc2, 0x0d, 0x8f, 0x13, 0xdb, 0x18, 0x1a,
	0xa3, 0x76, 0x50, 0x00, 0xe6, 0x80, 0x95, 0x95, 0x44, 0xdb, 0xd4, 0x89, 0x07, 0xec, 0x4e, 0xe1,
	0xd3, 0x63, 0x29, 0xca, 0x44, 0x4a, 0xc8, 0x6c, 0x78, 0x4b, 0x79, 0x18, 0x22, 0x91, 0x56, 0xb3,
	0x82, 0x0a, 0xba, 0x63, 0x60, 0xff, 0x09, 0xa5, 0x5f, 0xf4, 0x7a, 0xb4, 0xb6, 0x7b, 0x69, 0xc2,
	0x87, 0x1a, 0xf9, 0x35, 0xf5, 0xbd, 0x8e, 0xf9, 0xd2, 0x0c, 0x8d, 0xfa, 0x0c, 0x6c, 0x00, 0xed,
	0x55, 0x2c, 0x49, 0xfd, 0xe5, 0x1b, 0xb4, 0x9b, 0x3a, 0xb9, 0x0f, 0xec, 0x7e, 0x26, 0xbc, 0x4c,
	0xb6, 0x8a, 0x9f, 0x15, 0x76, 0x7e, 0x03, 0xfc, 0xc3, 0x50, 0xa2, 0x9a, 0x8b, 0x08, 0x77, 0x95,
	0x2f, 0x78, 0x92, 0x63, 0x35, 0x81, 0x06, 0x8c, 0x41, 0x93, 0x30, 0x55, 0xba, 0x1d, 0x2b, 0xd0,
	0x6f, 0xe7, 0x27, 0x58, 0xbe, 0x14, 0xa7, 0x18, 0x2a, 0x62, 0x5f, 0xa1, 0x93, 0x15, 0xef, 0x65,
	0x1c, 0xed, 0xa6, 0x69, 0x8c, 0xda, 0x01, 0x94, 0xa1, 0x45, 0x44, 0xd3, 0x3b, 0x03, 0x7a, 0x07,
	0x16, 0xfc, 0xf1, 0x17, 0x6c, 0x0b, 0xbd, 0xba, 0xeb, 0xec, 0xfb, 0xa4, 0x76, 0x13, 0xcf, 0xae,
	0xd7, 0xf9, 0x71, 0x9c, 0x54, 0x58, 0xeb, 0x3a, 0x57, 0x37, 0xb7, 0xd7, 0x66, 0xdf, 0x7d, 0xe7,
	0x85, 0x9a, 0x50, 0xf9, 0x34, 0x33, 0xc6, 0xec, 0x0c, 0x3a, 0x07, 0xad, 0xb0, 0x61, 0x5d, 0xf0,
	0xe9, 0x56, 0x9d, 0x6f, 0x47, 0x18, 0x65, 0xbd, 0xcf, 0xba, 0xde, 0x7b, 0xb7, 0xab, 0xcf, 0xba,
	0x64, 0xce, 0x8c, 0xf1, 0xc9, 0x1b, 0x7d, 0xad, 0xbf, 0xee, 0x03, 0x00, 0x00, 0xff, 0xff, 0x89,
	0xaa, 0xd3, 0xb2, 0xf6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserProfileAPIClient is the client API for UserProfileAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserProfileAPIClient interface {
	CreatePassword(ctx context.Context, in *CreatePasswordRequest, opts ...grpc.CallOption) (*CreatePasswordResponse, error)
	UserProfile(ctx context.Context, in *UserProfileRequest, opts ...grpc.CallOption) (*UserProfileResponse, error)
}

type userProfileAPIClient struct {
	cc *grpc.ClientConn
}

func NewUserProfileAPIClient(cc *grpc.ClientConn) UserProfileAPIClient {
	return &userProfileAPIClient{cc}
}

func (c *userProfileAPIClient) CreatePassword(ctx context.Context, in *CreatePasswordRequest, opts ...grpc.CallOption) (*CreatePasswordResponse, error) {
	out := new(CreatePasswordResponse)
	err := c.cc.Invoke(ctx, "/user_profile.UserProfileAPI/CreatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileAPIClient) UserProfile(ctx context.Context, in *UserProfileRequest, opts ...grpc.CallOption) (*UserProfileResponse, error) {
	out := new(UserProfileResponse)
	err := c.cc.Invoke(ctx, "/user_profile.UserProfileAPI/UserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProfileAPIServer is the server API for UserProfileAPI service.
type UserProfileAPIServer interface {
	CreatePassword(context.Context, *CreatePasswordRequest) (*CreatePasswordResponse, error)
	UserProfile(context.Context, *UserProfileRequest) (*UserProfileResponse, error)
}

func RegisterUserProfileAPIServer(s *grpc.Server, srv UserProfileAPIServer) {
	s.RegisterService(&_UserProfileAPI_serviceDesc, srv)
}

func _UserProfileAPI_CreatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileAPIServer).CreatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_profile.UserProfileAPI/CreatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileAPIServer).CreatePassword(ctx, req.(*CreatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileAPI_UserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileAPIServer).UserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_profile.UserProfileAPI/UserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileAPIServer).UserProfile(ctx, req.(*UserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserProfileAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_profile.UserProfileAPI",
	HandlerType: (*UserProfileAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePassword",
			Handler:    _UserProfileAPI_CreatePassword_Handler,
		},
		{
			MethodName: "UserProfile",
			Handler:    _UserProfileAPI_UserProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/user_profile.proto",
}
