// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/user_profile.proto

package user_profile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserProfileRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserProfileRequest) Reset()         { *m = GetUserProfileRequest{} }
func (m *GetUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserProfileRequest) ProtoMessage()    {}
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef67784dca69381c, []int{0}
}

func (m *GetUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserProfileRequest.Unmarshal(m, b)
}
func (m *GetUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserProfileRequest.Merge(m, src)
}
func (m *GetUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserProfileRequest.Size(m)
}
func (m *GetUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserProfileRequest proto.InternalMessageInfo

func (m *GetUserProfileRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserProfileResponse struct {
	Profileimage         string   `protobuf:"bytes,1,opt,name=profileimage,proto3" json:"profileimage,omitempty"`
	Profiledescription   string   `protobuf:"bytes,2,opt,name=profiledescription,proto3" json:"profiledescription,omitempty"`
	Endorsements         []string `protobuf:"bytes,3,rep,name=endorsements,proto3" json:"endorsements,omitempty"`
	Currentprojects      []string `protobuf:"bytes,4,rep,name=currentprojects,proto3" json:"currentprojects,omitempty"`
	Previousprojects     []string `protobuf:"bytes,5,rep,name=previousprojects,proto3" json:"previousprojects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserProfileResponse) Reset()         { *m = GetUserProfileResponse{} }
func (m *GetUserProfileResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserProfileResponse) ProtoMessage()    {}
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef67784dca69381c, []int{1}
}

func (m *GetUserProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserProfileResponse.Unmarshal(m, b)
}
func (m *GetUserProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserProfileResponse.Marshal(b, m, deterministic)
}
func (m *GetUserProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserProfileResponse.Merge(m, src)
}
func (m *GetUserProfileResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserProfileResponse.Size(m)
}
func (m *GetUserProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserProfileResponse proto.InternalMessageInfo

func (m *GetUserProfileResponse) GetProfileimage() string {
	if m != nil {
		return m.Profileimage
	}
	return ""
}

func (m *GetUserProfileResponse) GetProfiledescription() string {
	if m != nil {
		return m.Profiledescription
	}
	return ""
}

func (m *GetUserProfileResponse) GetEndorsements() []string {
	if m != nil {
		return m.Endorsements
	}
	return nil
}

func (m *GetUserProfileResponse) GetCurrentprojects() []string {
	if m != nil {
		return m.Currentprojects
	}
	return nil
}

func (m *GetUserProfileResponse) GetPreviousprojects() []string {
	if m != nil {
		return m.Previousprojects
	}
	return nil
}

type UpdateUserProfileRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Profileimage         string   `protobuf:"bytes,2,opt,name=profileimage,proto3" json:"profileimage,omitempty"`
	Profiledescription   string   `protobuf:"bytes,3,opt,name=profiledescription,proto3" json:"profiledescription,omitempty"`
	Currentprojects      []string `protobuf:"bytes,4,rep,name=currentprojects,proto3" json:"currentprojects,omitempty"`
	Previousprojects     []string `protobuf:"bytes,5,rep,name=previousprojects,proto3" json:"previousprojects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserProfileRequest) Reset()         { *m = UpdateUserProfileRequest{} }
func (m *UpdateUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserProfileRequest) ProtoMessage()    {}
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef67784dca69381c, []int{2}
}

func (m *UpdateUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserProfileRequest.Unmarshal(m, b)
}
func (m *UpdateUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserProfileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserProfileRequest.Merge(m, src)
}
func (m *UpdateUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserProfileRequest.Size(m)
}
func (m *UpdateUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserProfileRequest proto.InternalMessageInfo

func (m *UpdateUserProfileRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserProfileRequest) GetProfileimage() string {
	if m != nil {
		return m.Profileimage
	}
	return ""
}

func (m *UpdateUserProfileRequest) GetProfiledescription() string {
	if m != nil {
		return m.Profiledescription
	}
	return ""
}

func (m *UpdateUserProfileRequest) GetCurrentprojects() []string {
	if m != nil {
		return m.Currentprojects
	}
	return nil
}

func (m *UpdateUserProfileRequest) GetPreviousprojects() []string {
	if m != nil {
		return m.Previousprojects
	}
	return nil
}

type UpdateUserProfileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserProfileResponse) Reset()         { *m = UpdateUserProfileResponse{} }
func (m *UpdateUserProfileResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserProfileResponse) ProtoMessage()    {}
func (*UpdateUserProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef67784dca69381c, []int{3}
}

func (m *UpdateUserProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserProfileResponse.Unmarshal(m, b)
}
func (m *UpdateUserProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserProfileResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserProfileResponse.Merge(m, src)
}
func (m *UpdateUserProfileResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserProfileResponse.Size(m)
}
func (m *UpdateUserProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserProfileResponse proto.InternalMessageInfo

func (m *UpdateUserProfileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*GetUserProfileRequest)(nil), "user_profile.GetUserProfileRequest")
	proto.RegisterType((*GetUserProfileResponse)(nil), "user_profile.GetUserProfileResponse")
	proto.RegisterType((*UpdateUserProfileRequest)(nil), "user_profile.UpdateUserProfileRequest")
	proto.RegisterType((*UpdateUserProfileResponse)(nil), "user_profile.UpdateUserProfileResponse")
}

func init() { proto.RegisterFile("protos/user_profile.proto", fileDescriptor_ef67784dca69381c) }

var fileDescriptor_ef67784dca69381c = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0xfa, 0xf4, 0x79, 0x19, 0x4a, 0xfb, 0xb8, 0x54, 0x4d, 0x83, 0x42, 0x89, 0xa2,
	0xa5, 0x60, 0x03, 0x8a, 0x17, 0x6f, 0x9e, 0xc4, 0x5b, 0x29, 0xf4, 0x2c, 0x31, 0x1d, 0xc3, 0x4a,
	0xbb, 0xbb, 0xee, 0x6c, 0xf4, 0xae, 0x1f, 0xc0, 0x83, 0x1f, 0xcd, 0x9b, 0x67, 0xf1, 0x73, 0x48,
	0x36, 0x51, 0x9a, 0xbe, 0x68, 0x2f, 0x1e, 0xe7, 0x9f, 0xdf, 0x4c, 0xfe, 0xf3, 0xb2, 0xd0, 0x52,
	0x5a, 0x1a, 0x49, 0x61, 0x4a, 0xa8, 0x2f, 0x94, 0x96, 0x57, 0x7c, 0x8c, 0x3d, 0xab, 0xb1, 0xda,
	0xb4, 0xe6, 0x6f, 0x25, 0x52, 0x26, 0x63, 0x0c, 0x23, 0xc5, 0xc3, 0x48, 0x08, 0x69, 0x22, 0xc3,
	0xa5, 0xa0, 0x9c, 0x0d, 0x0e, 0x60, 0xfd, 0x0c, 0xcd, 0x90, 0x50, 0xf7, 0x73, 0x7e, 0x80, 0x37,
	0x29, 0x92, 0x61, 0x4d, 0xa8, 0xe2, 0x24, 0xe2, 0x63, 0xcf, 0x69, 0x3b, 0x9d, 0x7f, 0x83, 0x3c,
	0x08, 0xde, 0x1c, 0xd8, 0x98, 0xe5, 0x49, 0x49, 0x41, 0xc8, 0x02, 0xa8, 0x15, 0xbf, 0xe4, 0x93,
	0x28, 0xc1, 0x22, 0xaf, 0xa4, 0xb1, 0x1e, 0xb0, 0x22, 0x1e, 0x21, 0xc5, 0x9a, 0xab, 0xcc, 0x8a,
	0xe7, 0x5a, 0x72, 0xc1, 0x97, 0xac, 0x26, 0x8a, 0x91, 0xd4, 0x84, 0x13, 0x14, 0x86, 0xbc, 0x4a,
	0xbb, 0x92, 0xd5, 0x9c, 0xd6, 0x58, 0x07, 0x1a, 0x71, 0xaa, 0x35, 0x0a, 0xa3, 0xb4, 0xbc, 0xc6,
	0xd8, 0x90, 0xf7, 0xcb, 0x62, 0xb3, 0x32, 0xeb, 0xc2, 0x7f, 0xa5, 0xf1, 0x96, 0xcb, 0x94, 0x3e,
	0xd1, 0xaa, 0x45, 0xe7, 0xf4, 0xe0, 0xc5, 0x01, 0x6f, 0xa8, 0x46, 0x91, 0xc1, 0x55, 0x67, 0x33,
	0x37, 0x00, 0x77, 0xe5, 0x01, 0x54, 0x96, 0x0e, 0xe0, 0x67, 0x9a, 0x3b, 0x86, 0xd6, 0x82, 0xde,
	0x8a, 0x3d, 0x7a, 0xf0, 0x87, 0xd2, 0x38, 0x46, 0x22, 0xdb, 0xde, 0xdf, 0xc1, 0x47, 0x78, 0xf8,
	0xe8, 0x42, 0x7d, 0x2a, 0xe3, 0xb4, 0x7f, 0xce, 0xee, 0xa0, 0x5e, 0x3e, 0x07, 0xb6, 0xd3, 0x2b,
	0x5d, 0xe4, 0xc2, 0xe3, 0xf2, 0x77, 0xbf, 0x86, 0x72, 0x27, 0x81, 0x7f, 0xff, 0xfc, 0xfa, 0xe4,
	0x36, 0x83, 0x46, 0x98, 0xa0, 0xc9, 0x12, 0x0a, 0xfe, 0xc4, 0xe9, 0xb2, 0x07, 0x07, 0xd6, 0xe6,
	0x7a, 0x60, 0x7b, 0xe5, 0xba, 0xcb, 0x16, 0xe8, 0xef, 0x7f, 0xcb, 0x15, 0x16, 0xb6, 0xad, 0x85,
	0xcd, 0x80, 0x85, 0xa9, 0x65, 0xca, 0x2e, 0x2e, 0x7f, 0xdb, 0x47, 0x74, 0xf4, 0x1e, 0x00, 0x00,
	0xff, 0xff, 0x0d, 0x1e, 0xd2, 0x2d, 0x8d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserProfileAPIClient is the client API for UserProfileAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserProfileAPIClient interface {
	GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
	UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UpdateUserProfileResponse, error)
}

type userProfileAPIClient struct {
	cc *grpc.ClientConn
}

func NewUserProfileAPIClient(cc *grpc.ClientConn) UserProfileAPIClient {
	return &userProfileAPIClient{cc}
}

func (c *userProfileAPIClient) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	out := new(GetUserProfileResponse)
	err := c.cc.Invoke(ctx, "/user_profile.UserProfileAPI/GetUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileAPIClient) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UpdateUserProfileResponse, error) {
	out := new(UpdateUserProfileResponse)
	err := c.cc.Invoke(ctx, "/user_profile.UserProfileAPI/UpdateUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProfileAPIServer is the server API for UserProfileAPI service.
type UserProfileAPIServer interface {
	GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error)
	UpdateUserProfile(context.Context, *UpdateUserProfileRequest) (*UpdateUserProfileResponse, error)
}

func RegisterUserProfileAPIServer(s *grpc.Server, srv UserProfileAPIServer) {
	s.RegisterService(&_UserProfileAPI_serviceDesc, srv)
}

func _UserProfileAPI_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileAPIServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_profile.UserProfileAPI/GetUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileAPIServer).GetUserProfile(ctx, req.(*GetUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileAPI_UpdateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileAPIServer).UpdateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_profile.UserProfileAPI/UpdateUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileAPIServer).UpdateUserProfile(ctx, req.(*UpdateUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserProfileAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_profile.UserProfileAPI",
	HandlerType: (*UserProfileAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserProfile",
			Handler:    _UserProfileAPI_GetUserProfile_Handler,
		},
		{
			MethodName: "UpdateUserProfile",
			Handler:    _UserProfileAPI_UpdateUserProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/user_profile.proto",
}
